#!/bin/bash
# This script fakes the output of ifconfig for the singular purpose of meeting
# an OBSR requirement in obtaining the MAC address (for licensing)


if [[ $OBSR_MAC ]]; then
  if [[ $OBSR_MAC = "RANDOM" ]]; then
    MAC=$(echo -n "00"; dd bs=1 count=5 if=/dev/random 2>/dev/null | hexdump -v -e '/1 ":%02X"')
  else
    MAC=$OBSR_MAC
  fi
else
  MAC=$(cat /sys/class/net/eth*/address)
fi

echo "    ether $MAC"
