version: '2'

services:
  obsr:
    build: .
    image: yoff/obsr:latest
    hostname: obsr.example.com
    restart: on-failure
    mem_limit: 4g
    #volumes:
    #  - ./obsr:/obsr
    entrypoint: /docker-entrypoint.sh
    ports:
      - "9444-9464"
    environment:
      - TZ=America/Phoenix

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/certs:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - "obsr"
