version: '2'

services:
  obsr:
    image: centos:latest
    hostname: obsr.example.com
    restart: on-failure
    mem_limit: 4g
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./obsr:/obsr
    entrypoint: /docker-entrypoint.sh
    ports:
     - "80:8080"
     - "443:8443"
     - "9444-9464:9444-9464"
    environment:
      - TZ=America/Phoenix
