version: '2'

services:
  obsr:
    build: .
    image: yoff/obsr:latest
    hostname: obsr.example.com
    restart: on-failure
    mem_limit: 4g
    #volumes:
    #  - ./obsr:/obsr
    ports:
      - "80:8080"
      - "443:8443"
      - "9444-9464"
    environment:
      - TZ=America/Phoenix
